### ISSUE TITLE
Is it possible to reject changes in units and return to classic balance?

### ISSUE THREAD

**Issue by kamalist** [toyknight/project_aeii#14]
Some people are interested if it is possible to create a game modification with the same units, parameters and effect as classical Symbian AEII?

**Comment by toyknight** [comment]
Well, actually we are not planning to do that. I think you should be quite aware of the problems with original version, you just need to level archers and golems to win the game, other units' cost efficiency simply have no match for these two. So we make all the changes in this version is to make the game more playable, that is, briefly speaking, trying to give each unit a fair chance to show up in the battle, especially in the PVP mode.
However if you have any confusion about the settings of this version, please point it out, I will make explanation to you if I can.

**Comment by kamalist** [comment]
I'm quite confused about how poison does work and what causes it

**Comment by toyknight** [comment]
There are two ways that may cause poison effects:
1. Being attacked by a unit with `Poisoner` ability (for more detail you can refer to the in-game help page). This poison effect lasts for two rounds.
2. Standby on tomes. This will remove the tomb but the unit will be poisoned. This poison effect lasts for one round.

There are also some ways to work against poison effect:
1. Using spirit's `Refresh Aura` to clear negative effect on allies.
2. Using berserker to apply `Inspired` buff on allies then they will be immune to negative effects.
3. Using units with `Undead` ability. The poison effect on them will turn into HP recovery.
