### ISSUE TITLE
After you lose a commander in campaign, stage is failed even if you have a castle and income

### ISSUE THREAD

**Issue by DmitryRumiantsev** [toyknight/project_aeii#16]
The titles says it. It happens in the "Battle of Thorin" campaign (I didn't check it for the other ones) and it is especially frustrating during the last mission.  Can this be fixed?

**Comment by toyknight** [comment]
In the campaign yes, I think in almost all the stages losing commander means losing the stage. Campaign rules are usually quite different with the skirmish mode, so just try to get used to that ;)

BTW for the last stage of 'Battle of Thorin' the haven's fury will not hit commanders if you have other units, so personally I don't think it's pretty much a problem.

**Comment by DmitryRumiantsev** [comment]
Thank you for the reply. But why do we have an option to purchase a commander in some missions, if we can't possibly use it? The prequl seems fairer in that respect, because often this option is not present and it's absence warns you that you will fail, should the commander die.
But if what you say about the last mission of the original campaign is true, then this is not a big deal. I didn't have time to see it, because I lost a commander around turn 3 (to check if I would lose the stage). In the original campaign, the last mission was unfair, but beatable by carefully constructing your defences around few key spots and golems. But in this game it seems to be more of a challenge,  with heaven's fury inflicting 99 damage, the ability to relatively easily destroy any defending unit and player's inability to lose a commander. 
I really enjoy this game and I like your new balance very much (although now soldier seems boring even compared to skeleton). So I would like to sincerely thank you for putting so much effort into it and for providing the players with something nostalgically appealing yet fun, interesting and challenging in a brand new way.

**Comment by toyknight** [comment]
To be frank, the reason why commander buying option appears in some stages is to let AI able to buy it, since player and AI have exactly the same unit buying options. I'm not planning to change this in the near future so I hope you can get used to it ;)

**Comment by DmitryRumiantsev** [comment]
Yes, I understand. In fact, I have already gotten used to that, having completed one campaign and almost completed another. Thank you for the explanation.
I guess this issue is closed now.
