### ISSUE TITLE
为何不支持中文输入呢 ？

### ISSUE THREAD

**Issue by enefry** [toyknight/project_aeii#23]
中文编码：u4e00-u9fa5
好像修改这里就OK吧。
public class InputFilter implements TextField.TextFieldFilter {
   @Override
   public boolean acceptChar(TextField textField, char c) 
       boolean accept = ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || ('0' <= c && c <= '9') || c == '_' || c == ' '||(c>=0x4e00 && c<=0x9fa5);;
       return accept;
   }
}

**Comment by toyknight** [comment]
libgdx的内置TextField不支持IME输入，你要输入中文的话切到中文系统就好了。

**Comment by enefry** [comment]
Android平台可以用输入法啦。主要是被net.toyknight.aeii.utils.InputFilter拦截了。

**Comment by toyknight** [comment]
这个filter是在不允许中文输入的地方用的，比如用户名和地图名的输入。不加这个filter的话你可以把中文粘贴进来。
