### ISSUE TITLE
BW's Warroom - 5. Rugged Canyon doesn't end

### ISSUE THREAD

**Issue by Ondrazar** [toyknight/project_aeii#46]
I recently finished this mission and it didn't end. I killed all units, occupied all houses and the castle and the game keeps going on. The computer gets 0 income and ends the turn over and over again.

Playing on Android, 0% DR.

**Comment by toyknight** [comment]
Hmmm, I've heard of this issue before. Will fix it asap.

**Comment by toyknight** [comment]
Fixed in 2.1.7
