### ISSUE TITLE
please guide fork

### ISSUE THREAD

**Issue by PhanThanhHuy** [toyknight/project_aeii#50]
how to get my fork updated like your fork

**Comment by toyknight** [comment]
Please use Github desktop app, so you can update from original branch and get better fork management. Check the link below.
https://desktop.github.com/

**Comment by PhanThanhHuy** [comment]
I only have android, is there a way to do that on android?

**Comment by toyknight** [comment]
Try this, looks promising.
https://play.google.com/store/apps/details?id=com.fastaccess.github

**Comment by PhanThanhHuy** [comment]
My device does not support github application.
But now I have updated your Fork by deleting my fork and creating a new Fork on the chrome browser.
