### ISSUE TITLE
有部队占据城堡位置时，无法进入城堡菜单

### ISSUE THREAD

**Issue by Majirefy** [toyknight/project_aeii#6]
> by 喾新（132661853＊）

**Comment by Majirefy** [comment]
关于商店的话，必须城堡上没有单位，点城堡才会出现。硬性规定...原版一个球站在城堡上面可以守到天荒地老的情况不能再出现了。

**Comment by SheepYang1993** [comment]
习惯了老版。。。还以为这是BUG，原来是强制不能进入菜单了。。。
