### ISSUE TITLE
License and README.md

### ISSUE THREAD

**Issue by kamalist** [toyknight/project_aeii#8]
Hello! I have found that your project has no license attached. It is highly recommended for GitHub projects to have a license attached; otherwise people cannot legally use your project. Also it would be nice to attach some README.md with instructions about your project: how to execute, how to compile, how to contribute, etc.

**Comment by toyknight** [comment]
Commit 9f6fa3394d3da90e63e3b45f6d4a02af3acba0e9 and 7f09c54d1923382d57a617ba7f69357ac47b7a85 closes #8

**Comment by toyknight** [comment]
Commit 7f09c54d1923382d57a617ba7f69357ac47b7a85 and 9f6fa3394d3da90e63e3b45f6d4a02af3acba0e9 closes #8
